// Login
export const GET_CMS_PROFILE = 'GET_CMS_PROFILE';

// List Category
export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const GET_CATEGORY_DETAIL = 'GET_CATEGORY_DETAIL';

// List Upgrade Shop Request
export const GET_LIST_UPGRADE_SHOP_REQUEST = 'GET_LIST_UPGRADE_SHOP_REQUEST';
export const GET_UPGRADE_SHOP_REQUEST_DETAIL = 'GET_UPGRADE_SHOP_REQUEST_DETAIL';
export const GET_UPGRADE_SHOP_REQUEST_STATUS_COUNT = 'GET_UPGRADE_SHOP_REQUEST_STATUS_COUNT';

// C3006
export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT';

// C2001 : Turnover
export const GET_TURNOVER_BY_ORDER = 'GET_TURNOVER_BY_ORDER';
export const GET_TURNOVER_BY_AGE = 'GET_TURNOVER_BY_AGE';
export const GET_TURNOVER_BY_BEST_SALES = 'GET_TURNOVER_BY_BEST_SALES';

// C2010 : User management
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';

// C3004 : Store management
export const GET_ALL_STORES = 'GET_ALL_STORES';
export const GET_STORE_DETAIL = 'GET_STORE_DETAIL';

// Payout history
export const GET_TURNOVER_PAYOUT_HISTORY = 'GET_TURNOVER_PAYOUT_HISTORY';
export const GET_TURNOVER_PAYOUT_DETAIL_STORE = 'GET_TURNOVER_PAYOUT_DETAIL_STORE';
export const GET_BANK_PRESENT_STORE = 'GET_BANK_PRESENT_STORE';
export const GET_BANK_RETRIEVE_STORE = 'GET_BANK_RETRIEVE_STORE';
export const GET_BANK_COUNT_STATUS = 'GET_BANK_COUNT_STATUS';
// C2002 : List live streams
export const GET_LIST_LIVE_STREAM = 'GET_LIST_LIVE_STREAM';

// C2012: User Chat Management
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_GROUP_CHAT_MESSENGER = 'GET_GROUP_CHAT_MESSENGER';

// C2005 : List orders
export const GET_LIST_ORDERS = 'GET_LIST_ORDERS';
export const USE_GET_ORDER_DETAIL = 'USE_GET_ORDER_DETAIL';

export const USE_GET_LIVE_STREAM_DETAIL = 'USE_GET_LIVE_STREAM_DETAIL';
